env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - "plugin:json/recommended"
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
