env:
  browser: true
  es2021: true
  cypress/globals: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:json/recommended'
  - prettier
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - eslint-plugin-cypress
rules:
  {
    'space-before-function-paren': ['error', 'never'],
    'comma-dangle': ['error', 'always-multiline'],
  }
