---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Environment
    command: |
      cp .env.example .env
      sed -i "s|http://localhost:3000|$(gp url 3000)|" .env
  - name: Database
    command: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: Server
    init: npm ci
    command: |
      gp env PLAYWRIGHT_BROWSERS_PATH=0
      eval $(gp env -e)
      gp ports await 27017
      nvm install 18
      npm run dev

ports:
  - port: 3000
    onOpen: open-preview
    name: BioDrop
    description: The BioDrop website

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
