---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install npm dependencies
    init: |
      npm ci
      PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium
    command: |
      gp env PLAYWRIGHT_BROWSERS_PATH=0
      eval $(gp env -e)
      gp ports await 27017
      npm run dev
  - name: Mongo
    command: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
