---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install npm depdencies
    init: npm i
    command: |
      gp ports await 27017
      npm run dev
  - name: Mongo
    command: |
      mkdir -p /workspace/data && mongod --dbpath /workspace/data

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

image: gitpod/workspace-mongodb

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
