name: Testimonial
title: Testimonial
description: Make a testimonial for some user
labels: ["testimonial"]
body: 
  - type: input
    id: title
    attributes:
      label: Title
      description: An antitlement of your testimonial
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Title
      description: An antitlement of your testimonial
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A more exteded description of testimonial
    validations:
      required: true