name: Data Filenames Check

on:
  pull_request:
    paths:
      - "data/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Check changed files
        env:
          FILENAMES: ${{ steps.changed-files.outputs.all_changed_files }}
          USERNAME: ${{ github.actor }}
        run: |
          node .github/scripts/check-filenames.js
