name: Load profiles into DB
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Deploy to Vercel]

jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            data:
              - 'data/**'
      - name: load json files
        if: steps.changes.outputs.data == 'true'
        run: curl -f https://linkfree.io/api/system/reload?secret=${{ secrets.LINKFREE_API_SECRET }}
